version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: nexdns-frontend
    ports:
      - "3000:80"
    restart: always

  backend:
    build: ./backend
    container_name: nexdns-backend
    ports:
      - "8080:8080"
    restart: always
